permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: pygments
encoding: utf-8

kramdown:
  input: GFM

# 作者信息
author:
  name: 永进幽草
  email: 382@789.onmicrosoft.com
  link: http://0878.gearhostpreview.com/
  weibo: https://weibo.com/u/6336456792
  github: https://github.com/0878

# 站点信息
title: 永进舫
description: 永进舫(Jekyll);整理、记载关于工具/资源/生活/技术/读书/影音等经验和思考;
url: https://blog.lovejade.cn
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: /assets/images/nicejade-icon.jpg
# favicon: https://www.jeffjade.com/img/xuan.ico

# google analytics 设置
ga:
  id: UA-86109050-1
  url: http://0878.22web.org

# disqus 设置
#disqus:
  #shortname: 0878

#rake configuration on 2016-03-01
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: atom
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/nicejade.github.com/

theme: jekyll-theme-cayman